translate = ["!*"]
imports = ["!*"]
trusted = [
  "UInt64Put",
  "Assume",
  "RandomUint64",
  "AssumeNoStringOverflow",
  "Mutex*",
  "ProphId",
  # FIXME: add remaining functions
]
[bootstrap]
enabled = true
prelude = []
