dist: trusty
sudo: required
language: generic

# set up ocaml and opam
before_install:
  - sh <(curl -sL https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh)
  - eval $(opam config env)
env:
  global:
    - OCAML_VERSION=4.06
    - OPAM_VERSION=2.0.0
  matrix:
    - COQ_VERSION=master

install:
  - opam pin add -y coq "https://github.com/coq/coq.git#$COQ_VERSION"
script: make test

# cache opam-built compiler and packages
cache:
  directories:
    - $HOME/.opam
before_cache:
  - rm -rf $HOME/.opam/log

# note that this disables emails to commit authors
notifications:
  email:
    recipients:
      - tchajed@mit.edu
    # these are the defaults
    on_success: change
    on_failure: always
