dist: xenial
language: minimal

notifications:
  email:
    - tchajed@mit.edu
    - jtassaro@andrew.cmu.edu

branches:
  only:
    - master
      # for version tags of the form v0.1 or v0.1.1
    - /^v\d+\.\d+(\.\d+)?$/

services:
  - docker

env:
  global:
  - NJOBS="2"
  matrix:
  - COQ_IMAGE="coqorg/coq:dev"
  - COQ_IMAGE="coqorg/coq:8.9"

# On Travis cloning the gitlab dependencies fails due to a certificate error. In
# order to disable SSL verification for the submodule init, we have to tell
# Travis not to initialize submodules.
git:
  submodules: false

before_install:
  - git -c http.sslVerify=false submodule update --init --recursive

install: |
  # Prepare the COQ container
  docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/coq/demo -w /home/coq/demo ${COQ_IMAGE}
  docker exec COQ /bin/bash --login -c "
    # This bash script is double-quoted to interpolate Travis CI env vars:
    echo \"Build triggered by ${TRAVIS_EVENT_TYPE}\"
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
    set -ex  # -e = exit on failure; -x = trace for debug
    sudo apt-get update
    sudo apt-get install -y python3 python3-pip sqlite3
    pip3 install -r etc/requirements.txt
    #opam update -y
    opam switch \${COMPILER_EDGE}; eval \$(opam env)
    opam config list
    opam repo list
    opam list
    echo \"git log: https://github.com/coq/coq/commits/\$(opam info -f source-hash coq)\"
    "
before_script:
- |
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
    sudo chown -R coq:coq /home/coq/demo
    "
- source ./etc/ci/travis_keep_alive.sh

script:
- echo -e "${ANSI_YELLOW}Building ${TRAVIS_REPO_SLUG}...${ANSI_RESET}" && echo -en 'travis_fold:start:build\\r'
  # TODO: go back to running the test target once things work
- |
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
    set -ex
    make -j${NJOBS} -k ci
    "
- echo -en 'travis_fold:end:build\\r'

after_script:
  - docker stop COQ

after_success:
  - kill $PID_KEEP_ALIVE
