translate = [
  "LeaseID",
  "Txn",
  "Cmp",
  "KV",
  "OpOption",
  "TxnResponse",
  "Cluster",
  "GetResponse",
  "WatchResponse",
  "WatchChan",
  "Event",
  "Watcher",
  "Lease",
  "NoLease",
  "LeaseGrantResponse",
  "OpResponse",
  "EventTypeDelete",

  "PutResponse",
  "RangeResponse",
  "DeleteResponse",
  "opType",
  "Op",
  "Op.*",
  "OpPut",
  "OpGet",
  "OpDelete",
  "OpTxn",
  "With*",
  "!WithCompactPhysical",
  "!WithRequireLeader",
  "tRange", "tPut", "tDeleteRange", "tTxn",
  "SortTarget", "SortOrder", "SortOption",
  "SortBy*", "SortNone", "SortAscend", "SortDescend",
  "LeaseOp", "LeaseOption",
]

axiomatize = [
  "Client",
  "Op",
]

imports = [
  "go.etcd.io/etcd/api/v3/etcdserverpb",
  "go.etcd.io/etcd/api/v3/mvccpb",
]
