translate = [
  "Compare",
  "Compare_*",
  "isCompare_TargetUnion",
  "ResponseHeader",
  "RequestHeader",
  "InternalRaftRequest",

  "TxnRequest",
  "TxnResponse",

  "RangeRequest",
  "RangeRequest_*",
  "RangeResponse",

  "PutRequest",
  "PutResponse",

  "DeleteRangeRequest",
  "DeleteRangeResponse",

  "RequestOp",
  "ResponseOp",
  "isResponseOp_Response",
  "isRequestOp_Request",
  "ResponseOp_*",
  "RequestOp_*",
  "!*.String",             # Uses proto.proto
]

imports = ["!*", "go.etcd.io/etcd/api/v3/membershippb", "go.etcd.io/etcd/api/v3/mvccpb"]

trust_proofgen = true
