translate = [
  "Compare",
  "Compare_*",
  "isCompare_TargetUnion",
  "ResponseHeader",

  "TxnRequest",
  "TxnResponse",

  "RangeRequest",
  "RangeRequest_*",
  "RangeResponse",

  "PutRequest",
  "PutResponse",

  "DeleteRangeRequest",
  "DeleteRangeResponse",

  "RequestOp",
  "ResponseOp",
  "isResponseOp_Response",
  "isRequestOp_Request",
  "ResponseOp_*",
  "RequestOp_*",
  "!*.String", # Uses proto.proto
]

imports = [
  "!*",
]
